# Generated by Django 5.2.4 on 2026-06-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='finance_tra_categor_235d4a_idx',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['subcategory'], name='finance_tra_subcate_fe18bc_idx'),
        ),
    ]
