# Generated by Django 5.2.4 on 2026-06-04 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_transaction_finance_tra_categor_235d4a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color in #RRGGBB format. Generated automatically if blank.', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a hex value like #1A2B3C.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color in #RRGGBB format. Generated automatically if blank.', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a hex value like #1A2B3C.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color in #RRGGBB format. Generated automatically if blank.', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a hex value like #1A2B3C.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
