# Generated by Django 5.2.4 on 2026-06-04 06:37

import django.db.models.deletion
import finance.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("account_number", models.CharField(max_length=128, unique=True)),
                ("bank_name", models.CharField(blank=True, max_length=128)),
                ("currency", models.CharField(default="CZK", max_length=3)),
                ("owners", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CSVMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                ("delimiter", models.CharField(default=",", max_length=8)),
                ("quotechar", models.CharField(default='"', max_length=1)),
                ("encoding", models.CharField(default="utf-8-sig", max_length=64)),
                ("header_row", models.PositiveIntegerField(default=0)),
                ("date_format", models.CharField(default="%Y-%m-%d", max_length=64)),
                (
                    "fallback_date_formats",
                    models.JSONField(blank=True, default=finance.models.empty_list),
                ),
                ("decimal_separator", models.CharField(default=".", max_length=1)),
                (
                    "thousands_separator",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                ("default_currency", models.CharField(default="CZK", max_length=3)),
                (
                    "column_map",
                    models.JSONField(blank=True, default=finance.models.empty_dict),
                ),
                (
                    "categorization_fields",
                    models.JSONField(
                        blank=True,
                        default=finance.models.default_categorization_fields,
                        help_text="Logical transaction fields used to build the keyword matching text.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CSVImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=32,
                    ),
                ),
                ("loaded_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                (
                    "report",
                    models.JSONField(blank=True, default=finance.models.empty_dict),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.bankaccount",
                    ),
                ),
                (
                    "csv_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.csvmapping",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="default_csv_mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_accounts",
                to="finance.csvmapping",
            ),
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(blank=True, max_length=32)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="finance.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "subcategories",
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "include_terms",
                    models.JSONField(blank=True, default=finance.models.empty_list),
                ),
                (
                    "exclude_terms",
                    models.JSONField(blank=True, default=finance.models.empty_list),
                ),
                (
                    "want_need_investment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("want", "Want"),
                            ("need", "Need"),
                            ("investment", "Investment"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("is_ignored", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keywords",
                        to="finance.category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keywords",
                        to="finance.subcategory",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="keywords", to="finance.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_id", models.CharField(blank=True, max_length=128)),
                ("transaction_date", models.DateField()),
                ("posted_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="CZK", max_length=3)),
                (
                    "direction",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "counterparty_account_number",
                    models.CharField(blank=True, max_length=128),
                ),
                ("counterparty_name", models.CharField(blank=True, max_length=255)),
                ("transaction_type", models.CharField(blank=True, max_length=128)),
                ("variable_symbol", models.CharField(blank=True, max_length=128)),
                ("specific_symbol", models.CharField(blank=True, max_length=128)),
                ("constant_symbol", models.CharField(blank=True, max_length=128)),
                ("counterparty_note", models.TextField(blank=True)),
                ("my_note", models.TextField(blank=True)),
                ("other_note", models.TextField(blank=True)),
                (
                    "want_need_investment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("want", "Want"),
                            ("need", "Need"),
                            ("investment", "Investment"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("is_ignored", models.BooleanField(default=False)),
                (
                    "raw_data",
                    models.JSONField(blank=True, default=finance.models.empty_dict),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.bankaccount",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.category",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.csvimport",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.subcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finance.tag"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="tags",
            field=models.ManyToManyField(
                blank=True, through="finance.TransactionTag", to="finance.tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="subcategory",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="unique_subcategory_per_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="transactiontag",
            constraint=models.UniqueConstraint(
                fields=("transaction", "tag"), name="unique_tag_per_transaction"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_date"], name="finance_tra_transac_0cc58e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["direction"], name="finance_tra_directi_3b9fc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["amount"], name="finance_tra_amount_84277c_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["bank_account", "transaction_date"],
                name="finance_tra_bank_ac_38e023_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category", "subcategory"],
                name="finance_tra_categor_235d4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["want_need_investment"], name="finance_tra_want_ne_1f5bff_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("original_id__isnull", False),
                    models.Q(("original_id", ""), _negated=True),
                ),
                fields=("bank_account", "original_id"),
                name="unique_original_transaction_per_account",
            ),
        ),
    ]
