# Generated by Django 5.2.4 on 2026-06-12 05:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_alter_category_color_alter_subcategory_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                (
                    "ignore_internal_account_references",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically ignore transactions whose categorization text mentions another configured bank account number.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "finance settings",
            },
        ),
    ]
