# Generated by Django 5.2.4 on 2026-06-12 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_financesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="financesettings",
            name="internal_transfer_subcategory",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional subcategory assigned when a transaction mentions another configured bank account number.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="finance.subcategory",
            ),
        ),
    ]
