# Generated by Django 5.2.4 on 2026-06-15 11:42

import finance.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_financesettings_internal_transfer_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "filters",
                    models.JSONField(blank=True, default=finance.models.empty_dict),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
