# Generated by Django 5.2.4 on 2026-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_savedfilter"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_categorization_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["is_categorization_locked"],
                name="finance_tra_is_cate_f57caa_idx",
            ),
        ),
    ]
