# Generated by Codex on 2026-06-21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_transaction_is_categorization_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financesettings",
            name="default_currency",
            field=models.CharField(
                default="CZK",
                help_text=(
                    "Currency used for dashboard totals and converted transaction "
                    "amounts."
                ),
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("base_currency", models.CharField(max_length=3)),
                ("quote_currency", models.CharField(max_length=3)),
                (
                    "rate",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "source",
                    models.CharField(default="frankfurter", max_length=64),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "base_currency", "quote_currency"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="conversion_rate",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="conversion_rate_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="conversion_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("native", "Native currency"),
                    ("converted", "Converted"),
                    ("missing_rate", "Missing rate"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="converted_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="converted_currency",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AddIndex(
            model_name="exchangerate",
            index=models.Index(
                fields=["source", "base_currency", "quote_currency", "date"],
                name="finance_exc_source_953637_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exchangerate",
            index=models.Index(fields=["date"], name="finance_exc_date_ca33ea_idx"),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.UniqueConstraint(
                fields=("source", "base_currency", "quote_currency", "date"),
                name="unique_exchange_rate_per_source_pair_date",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["converted_currency"],
                name="finance_tra_convert_6fcd40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["conversion_status"],
                name="finance_tra_convers_93b755_idx",
            ),
        ),
    ]
