# Generated by Django 5.2.4 on 2026-06-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_exchange_rates_and_transaction_conversions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account_number", ""), _negated=True),
                fields=("account_number",),
                name="unique_nonblank_bank_account_number",
            ),
        ),
    ]
