# Generated by Codex on 2026-06-26

import uuid

import finance.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0009_alter_bankaccount_account_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalTransferMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confidence_score", models.PositiveIntegerField(default=0)),
                (
                    "match_reasons",
                    models.JSONField(blank=True, default=finance.models.empty_list),
                ),
                ("date_delta_days", models.PositiveIntegerField(default=0)),
                (
                    "incoming_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_internal_transfer_match",
                        to="finance.transaction",
                    ),
                ),
                (
                    "outgoing_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_internal_transfer_match",
                        to="finance.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
