# Generated by Django 5.2.4 on 2026-10-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_internal_transfer_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvmapping",
            name="file_format",
            field=models.CharField(
                choices=[("csv", "CSV"), ("camt053", "camt.053 XML (ISO 20022)")],
                default="csv",
                max_length=16,
            ),
        ),
    ]
